packages:
  - apps/*
  - packages/*

catalogs:
  build:
    '@rsbuild/plugin-less': 1.5.0
    '@rsbuild/plugin-react': 1.4.1
    '@modern-js/runtime': 2.68.5
    '@modern-js/plugin-tailwindcss': 2.68.5
    '@modern-js/app-tools': 2.68.5
    '@modern-js/tsconfig': 2.68.5
  react:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': 18.3.11
    '@types/react-dom': 18.3.1
    'react-i18next': 15.7.2
    i18next: 25.4.2
    'i18next-browser-languagedetector': 8.2.0
    zustand: 5.0.8

    '@types/jest': ~29.2.4

  lint:
    '@biomejs/biome': 1.9.4
    simple-git-hooks: ^2.11.1
    lint-staged: ~15.4.0

  node:
    typescript: ~5.7.3
    '@types/node': 18.11.9

  app:
    axios: ^1.9.0
    ahooks: ^3.9.4
    '@ahooksjs/use-url-state': ^3.5.1
    lodash-es: ^4.17.21
    qs: ^6.14.0
    '@types/lodash-es': ^4.17.12
    '@types/qs': ^6.14.0

  tailwindcss:
    '@tailwindcss/postcss': ^4.1.16
    tailwindcss: ^3.4.18
    postcss: ^8.5.3
    postcss-loader: ^8.1.1
    tw-animate-css: ^1.2.5
    tailwind-merge: ^3.2.0
    clsx: ^2.1.1

  semi-ui:
    '@douyinfe/semi-ui': ^2.85.0
