export enum AppRouter {
  Admin = '/admin',
  AdminCruise = '/admin/cruise',
  AdminCruiseList = '/admin/cruise/list',
  AdminCruiseListCreate = '/admin/cruise/list/create',
  AdminCruiseListDetail = '/admin/cruise/list/detail/[id]',
  AdminCruiseListEdit = '/admin/cruise/list/edit/[id]',
  AdminCruiseRoomCategory = '/admin/cruise/room-category',
  AdminCruiseRoomMessage = '/admin/cruise/room-message',
  AdminOrders = '/admin/orders',
  AdminOrdersList = '/admin/orders/list',
  AdminProducts = '/admin/products',
  AdminSettings = '/admin/settings',
  AdminSettingsTag = '/admin/settings/tag',
  AdminUsers = '/admin/users',
  AuthLogin = '/auth/login',
  AuthRegister = '/auth/register',
}
